version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
    timezone: Asia/Bangkok
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.41
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@google-cloud/storage"
    versions:
    - 5.7.3
    - 5.7.4
    - 5.8.0
    - 5.8.1
    - 5.8.2
    - 5.8.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: "@nestjs/common"
    versions:
    - 7.6.11
    - 7.6.12
    - 7.6.13
    - 7.6.14
    - 7.6.7
    - 7.6.8
    - 7.6.9
  - dependency-name: lint-staged
    versions:
    - 10.5.3
